const skills = [
  'Software Development',
  'Java',
  'JavaScript',
  'Programming',
  'Android',
  'Integration',
  'Agile',
  'Tools & Technologies',
  'HTML',
  'C++',
  'MySQL',
  'Node',
  'SQL',
  'CSS',
  'Perl',
  'Python',
  'apis',
  'deploying',
  'verbal',
  'Cascading Style Sheets (CSS)',
  'CSS',
  'Microsoft Office',
  'C',
  'PHP',
  'Microsoft Word',
  'C#',
  'Microsoft Excel',
  'MongoDB',
  'React.js',
  'NoSQL',
  'Git',
  'BigQuery',
  'RESTful',
  'webservices',
  'Google BigQuery',
  'Docker',
  'Nokia Qt',
  'QML',
  'Google Spanner',
  'Cassandra',
  'Pubsub',
  'Web Services API',
  'Kubernetes',
  'Computer',
  'Science',
];

export default skills.map(a => a.toLowerCase());
